blank_issues_enabled: true
contact_links:
  - name: "\U0001F914 All other questions, including if you're not sure what to do."
    url: https://stackoverflow.com/
    about: The issue tracker is only meant for bug reports, feature/plugin requests and plugin issues. Please ask your questions on the discussions forum and look for already existing answers.
  - name: "ðŸ¤” Questions and Code Owner Help"
    about: "In case there is some serios matter you about to discuss with me"
    url: https://ivankatliarchuk.github.io/
