name: 01-renovate

on:
  push:
    branches: [main, master]
  workflow_dispatch:
    inputs:
      dryrun:
        description: Perform a dry run by logging messages instead of creating/updating/deleting branches and PRs.
        required: true
        type: boolean
        default: true
  schedule:
    # https://crontab.guru/
    - cron: '0 4 * * *'

# https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  RENOVATE_CONFIG_FOLDER: renovate
  LOG_LEVEL: info
  FORCE_COLOR: true

jobs:
  renovate:
    runs-on: ubuntu-latest
    if: github.repository == 'ivankatliarchuk/.github'
    steps:
      - uses: actions/checkout@v4.2.0
        with:
          fetch-depth: '1'

      - name: repositories
        id: prepare
        run: |
          echo "node: $(node --version)"
          REPOSITORIES=$(./renovate/repositories.js)
          echo $REPOSITORIES
          echo "::set-output name=REPOSITORIES::$REPOSITORIES"
        env:
          RENOVATE_REPOSITORIES_FILE: ${{ env.RENOVATE_CONFIG_FOLDER }}/repositories.json

      # https://github.com/renovatebot/github-action install renovate app
      - name: execute-dependency-update
        uses: renovatebot/github-action@v40.2.8
        with:
          configurationFile: ${{ env.RENOVATE_CONFIG_FOLDER }}/config.js
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          USER_NAME: ${{ github.repository_owner }}
          RENOVATE_CONFIG_FOLDER: ${{ env.RENOVATE_CONFIG_FOLDER }}
          RENOVATE_DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
          LOG_LEVEL: info
          RENOVATE_REPOSITORIES: ${{ steps.prepare.outputs.repositories }}
          RENOVATE_DRY_RUN: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.dryrun || 'false' }}
