# @todo: sync with other repositories
---
name: auto-approve

on:
  pull_request_target

env:
  ACTOR: ivankatliarchuk

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/auto-approve-action@v2.1.0
      if: >
        github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]' || github.actor == ${{ env.ACTOR }}
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"

    - name: add-label-on-approve
      uses: actions/github-script@v3.1.1
      if: success()
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.issues.addLabels({
            issue_number: context.payload.pull_request.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            labels: [':bell: automerge','âœ… Approved']
          })
