# @todo: sync with other repositories
---
name: codeowners-merging

on:
  pull_request_target:
    branches: $default-branch
    types: [opened, synchronize, reopened]
  issue_comment: { types: created }
  pull_request_review: { types: submitted }

jobs:
  check:
    runs-on: ubuntu-latest
    steps:

      - name: checkout code
        uses: actions/checkout@v3.0.1
        with:
          fetch-depth: '1'
          submodules: 'recursive'

      - name: check if merge was approved by code owner
        uses: orta/code-owner-self-merge@1.6.5
        env:
          GITHUB_TOKEN: ${{  secrets.GITHUB_TOKEN }}
