name: synchronize.repo-content

on:
  schedule:
    - cron: '1 0 * * 5'
  workflow_dispatch:

env:
  OWNER: ivankatliarchuk
  REF: main

jobs:
  fetch-repo-info:
    name: extract repository data
    runs-on: ubuntu-latest
    if: github.repository != 'ivankatliarchuk/.github'
    steps:
      # Step 1: run a standard checkout action, provided by github
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: '1'
          submodules: 'recursive'

      - name: fetch-repo-name
        shell: bash
        env:
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          echo "can we read? $GITHUB_REPOSITORY"

  fork-sync:
    name: fork-sync
    if: github.repository != 'ivankatliarchuk/.github'
    needs: [fetch-repo-info]
    runs-on: ubuntu-latest
    steps:
      # Step 1: run a standard checkout action, provided by github
      - uses: actions/checkout@v2.3.4
        with:
          ref: ${{ env.REF }}
          fetch-depth: '1'
          submodules: 'recursive'

      # Step 2: Print a helpful timestamp for your records (not required, just nice)
      - name: timestamp
        id: envs
        run: echo "::set-output name=CURRENT_DATE::$(date -u +'%Y-%m-%dT%H-%M')"

      # Step 3: Display a message if 'sync' step had new commits (simple test)
      - uses: tgymnich/fork-sync@v1.4
        with:
          base: main
          head: main
          owner: ${{ env.OWNER }}
          auto_approve: false
          pr_title: |
            'fork: Forked from upstream "${{ github.workflow }} #${{ github.run_number }} #${{steps.envs.outputs.current_date}}" [skip ci]'
          pr_message: |
            ## Description

            Update current repository

            ## Workflow

            - Name: ${{ github.workflow }}
            - Run ID: ${{ github.run_id }}
            - Run Number: ${{ github.run_number }}

            _Auto-generated by [tgymnich/fork-sync][1]_

            [1]: https://github.com/tgymnich/fork-sync
