---
name: synchronize.labels

on:
  push:
    branches:
      - main
      - $default-branch
      - v.*
    paths:
      - .github/labels.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4.1.6
      # https://github.com/micnncim/action-label-syncer
      - uses: micnncim/action-label-syncer@v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
